# Generated by Django 3.2.5 on 2021-08-02 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('language', models.CharField(choices=[('cpp', 'C++'), ('python', 'Python')], default='cpp', max_length=20)),
                ('level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=8)),
                ('description', models.TextField(max_length=1000)),
                ('impKey', models.CharField(default='imp', max_length=1000)),
                ('contraints', models.TextField(blank=True, max_length=200, null=True)),
                ('example', models.TextField(blank=True, max_length=500, null=True)),
                ('inputf', models.TextField(max_length=1000, verbose_name='Input format')),
                ('outputf', models.TextField(max_length=1000, verbose_name='Output format')),
                ('explanation', models.TextField(blank=True, max_length=3000, null=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeRS.problem', verbose_name='Problem ID')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Constraint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.BigIntegerField()),
                ('variable', models.CharField(max_length=200)),
                ('upper_limit', models.BigIntegerField()),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeRS.problem', verbose_name='Problem ID')),
            ],
        ),
    ]
