# Generated by Django 3.2.3 on 2021-08-04 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeRS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solved',
            name='time',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
